"""
DevOpsAgent — GitSkill.
Handles branching, staging, committing, pushing, and PR creation.
Returns a DevOpsResult JSON.
"""
from __future__ import annotations

import json
import structlog
from datetime import timedelta

from temporalio import workflow
from temporalio.common import RetryPolicy

from agentex.lib import adk
from agentex.types.text_content import TextContent

with workflow.unsafe.imports_passed_through():
    from project.tools.devops import DEVOPS_VALID_TOOL_NAMES

logger = structlog.get_logger(__name__)

MAX_DEVOPS_TURNS = 16


def _format_pr_description(build_report: dict) -> str:
    """Render a structured PR description from the build report dict."""
    goal = build_report.get("goal", "")
    build_number = build_report.get("build_number", "?")
    prior_count = build_report.get("prior_episode_count", 0)
    tracks = build_report.get("tracks", [])
    tech_stack = build_report.get("tech_stack", [])
    files_modified = build_report.get("files_modified", 0)
    heal_cycles = build_report.get("heal_cycles", 0)
    inspector = build_report.get("inspector", {})
    reviewer = build_report.get("reviewer", {})
    security = build_report.get("security", {})
    active_facts = (build_report.get("active_facts") or "").strip()
    exclusions = build_report.get("explicit_exclusions", [])

    insp_passed = inspector.get("passed", False)
    insp_status = "✓ Passed" if insp_passed else f"✗ {heal_cycles} issue(s) found and fixed"
    rev_verdict = reviewer.get("verdict", "approve")
    rev_notes = reviewer.get("notes", "")
    rev_status = (
        "✓ Approved"
        if rev_verdict == "approve"
        else f"✗ Changes requested — {rev_notes[:120]}" if rev_notes else "✗ Changes requested"
    )
    sec_passed = security.get("passed", True)
    sec_count = security.get("finding_count", 0)
    sec_status = "✓ Clean" if sec_passed else f"⚠ {sec_count} finding(s) (non-blocking)"

    lines = [
        f"## Gantry Build Report — Build #{build_number} on this repo",
        "",
        f"**Goal:** {goal[:300]}",
        "",
        "### Plan",
    ]
    for t in tracks:
        label = t.get("label", "?")
        desc = t.get("description", "")
        lines.append(f"- **{label}**" + (f" — {desc}" if desc else ""))
    if tech_stack:
        lines.append(f"\nTech stack: {', '.join(str(s) for s in tech_stack)}")

    lines += [
        "",
        "### Execution",
        f"- {files_modified} file(s) modified · {heal_cycles} heal cycle(s)",
        f"- Inspector: {insp_status}",
        f"- Reviewer: {rev_status}",
        f"- Security: {sec_status}",
    ]

    # Memory context — only include meaningful fact lines
    fact_lines = [
        ln.strip() for ln in active_facts.splitlines()
        if ln.strip() and not ln.strip().startswith("[") and "No facts" not in ln
    ][:8]
    if fact_lines:
        lines += ["", "### What Gantry knew from previous builds"]
        for fl in fact_lines:
            lines.append(f"- {fl}")
        if prior_count > 0:
            lines.append(
                f"\n_Build #{build_number} on this repo — "
                f"{prior_count} prior episode{'s' if prior_count != 1 else ''} accumulated._"
            )
    elif prior_count == 0:
        lines += [
            "",
            "_First build on this repo — Gantry will learn from this run for future builds._",
        ]

    if exclusions:
        lines += ["", "### Explicitly not done"]
        for ex in exclusions[:5]:
            lines.append(f"- {ex}")

    lines += [
        "",
        "---",
        "_Generated by [Gantry](https://github.com/przhevalskiy/Gantry) — autonomous engineering factory_",
    ]
    return "\n".join(lines)

PLANNER_OPTIONS = {
    "start_to_close_timeout": timedelta(seconds=120),
    "retry_policy": RetryPolicy(maximum_attempts=2),
}
IO_OPTIONS = {
    "start_to_close_timeout": timedelta(seconds=30),
    "retry_policy": RetryPolicy(maximum_attempts=2),
}


@workflow.defn(name="DevOpsAgent")
class DevOpsAgent:
    """
    Handles all git operations and returns a DevOpsResult JSON.
    """

    @workflow.run
    async def run(
        self,
        goal: str,
        repo_path: str,
        branch_name: str,
        parent_task_id: str,
        build_summary: str = "",
        changed_files: list[str] | None = None,
        build_report: dict | None = None,
    ) -> str:
        log = logger.bind(parent_task_id=parent_task_id, branch=branch_name)
        log.info("devops_started")

        await adk.messages.create(
            task_id=parent_task_id,
            content=TextContent(
                author="agent",
                content=f"[DevOps] Staging changes on branch '{branch_name}'...",
            ),
        )

        if changed_files:
            _files_str = "\n".join(f"  - {f}" for f in changed_files[:40])
            _stage_instruction = (
                f"3. Stage ONLY the files created/modified by this build:\n{_files_str}\n"
                "   Call git_add with exactly those paths. "
                "   Do NOT use paths=['.'] — that would accidentally commit unrelated files.\n"
                "   If git_status shows additional relevant files not in the list above, add them too.\n"
            )
        else:
            _stage_instruction = (
                "3. Run git_status, then stage ONLY the files that differ from HEAD.\n"
                "   Do NOT use paths=['.'] blindly — inspect git_status output first and add only changed files.\n"
            )

        _pr_description = _format_pr_description(build_report) if build_report else ""
        _pr_instruction = (
            "6. Create a pull request with create_pull_request. "
            "Use the following as the PR body VERBATIM — do not rewrite or summarise it:\n"
            f"<pr_body>\n{_pr_description}\n</pr_body>\n"
            if _pr_description
            else "6. Optionally create a pull request with create_pull_request.\n"
        )

        task_prompt = (
            f"You are the DevOps agent. Your goal:\n{goal}\n\n"
            f"Repository root: {repo_path}\n"
            f"Target branch: {branch_name}\n"
            f"Build summary: {build_summary}\n\n"
            "Instructions:\n"
            "1. Run git_status to see what changed.\n"
            "2. Create the branch with git_create_branch.\n"
            f"{_stage_instruction}"
            "4. Commit with a descriptive conventional commit message.\n"
            "5. Push the branch with git_push.\n"
            f"{_pr_instruction}"
            "7. Optionally run run_migration if the build added new migrations.\n"
            "8. Optionally deploy if a platform token is configured (use deploy with platform='auto').\n"
            f"9. Call report_devops with the branch, commit SHA, PR URL, and summary.\n\n"
            f"For memory_read use repo_path='{repo_path}'."
        )

        context: list[dict] = []

        for turn in range(MAX_DEVOPS_TURNS):
            raw = await workflow.execute_activity(
                "plan_devops_step",
                args=[task_prompt, context, parent_task_id],
                **PLANNER_OPTIONS,
            )
            context = raw["context"]

            if raw["type"] == "devops":
                devops_data = raw["devops_data"]
                tool_use_id = raw["tool_use_id"]
                context = context + [{
                    "role": "user",
                    "content": [{"type": "tool_result", "tool_use_id": tool_use_id, "content": "DevOps recorded."}],
                }]
                log.info("devops_done", branch=devops_data.get("branch"), pr=devops_data.get("pr_url"))
                await adk.messages.create(
                    task_id=parent_task_id,
                    content=TextContent(
                        author="agent",
                        content=(
                            f"[DevOps] ✓ Branch '{devops_data.get('branch')}' pushed. "
                            + (f"PR: {devops_data.get('pr_url')}" if devops_data.get("pr_url") else "")
                        ),
                    ),
                )
                return json.dumps(devops_data)

            if raw["type"] == "final":
                log.warning("devops_no_report_tool", turn=turn)
                return json.dumps({"branch": branch_name, "success": True, "summary": raw["answer"]})

            if raw["type"] == "error":
                log.warning("devops_planner_error", message=raw.get("message"))
                break

            tool_name = raw["tool_name"]
            tool_use_id = raw["tool_use_id"]
            tool_input = raw["tool_input"]

            if tool_name not in DEVOPS_VALID_TOOL_NAMES:
                context = context + [{
                    "role": "user",
                    "content": [{"type": "tool_result", "tool_use_id": tool_use_id,
                                 "content": f"Unknown tool '{tool_name}'."}],
                }]
                continue

            await adk.messages.create(
                task_id=parent_task_id,
                content=TextContent(
                    author="agent",
                    content=f"[DevOps] {tool_name}",
                ),
            )

            tool_result = await self._dispatch(tool_name, tool_input)

            context = context + [{
                "role": "user",
                "content": [{"type": "tool_result", "tool_use_id": tool_use_id, "content": str(tool_result)}],
            }]

        log.warning("devops_max_turns")
        return json.dumps({"branch": branch_name, "success": False, "summary": "DevOps hit max turns."})

    async def _dispatch(self, tool_name: str, tool_input: dict) -> str:
        cwd = tool_input.get("cwd")
        if tool_name == "git_status":
            return await workflow.execute_activity(
                "swarm_git_status", args=[cwd], **IO_OPTIONS
            )
        if tool_name == "git_create_branch":
            return await workflow.execute_activity(
                "swarm_git_create_branch",
                args=[tool_input.get("branch_name", ""), cwd],
                **IO_OPTIONS,
            )
        if tool_name == "git_add":
            return await workflow.execute_activity(
                "swarm_git_add",
                args=[tool_input.get("paths", ["."]), cwd],
                **IO_OPTIONS,
            )
        if tool_name == "git_commit":
            return await workflow.execute_activity(
                "swarm_git_commit",
                args=[tool_input.get("message", "chore: swarm commit"), cwd],
                **IO_OPTIONS,
            )
        if tool_name == "git_push":
            return await workflow.execute_activity(
                "swarm_git_push",
                args=[tool_input.get("branch_name", ""), cwd],
                **IO_OPTIONS,
            )
        if tool_name == "create_pull_request":
            return await workflow.execute_activity(
                "swarm_create_pull_request",
                args=[
                    tool_input.get("title", ""),
                    tool_input.get("body", ""),
                    tool_input.get("head_branch", ""),
                    tool_input.get("base_branch", "main"),
                    cwd,
                ],
                **IO_OPTIONS,
            )
        if tool_name == "run_migration":
            return await workflow.execute_activity(
                "swarm_run_migration",
                args=[tool_input.get("tool", "auto"), cwd, tool_input.get("command")],
                start_to_close_timeout=timedelta(seconds=180),
                retry_policy=RetryPolicy(maximum_attempts=1),
            )
        if tool_name == "deploy":
            return await workflow.execute_activity(
                "swarm_deploy",
                args=[tool_input.get("platform", "auto"), cwd],
                start_to_close_timeout=timedelta(seconds=360),
                retry_policy=RetryPolicy(maximum_attempts=1),
            )
        if tool_name == "memory_read":
            return await workflow.execute_activity(
                "swarm_memory_read",
                args=[tool_input.get("repo_path", "."), tool_input.get("keys")],
                **IO_OPTIONS,
            )
        if tool_name == "memory_write":
            return await workflow.execute_activity(
                "swarm_memory_write",
                args=[tool_input.get("key", ""), tool_input.get("value", ""), tool_input.get("repo_path", "."), "devops"],
                **IO_OPTIONS,
            )
        return f"Error: tool '{tool_name}' not dispatched."
