import { STORAGE_KEY, type StorePulseState, type StoreReport } from './types';

function empty(): StorePulseState {
  return { version: 1, reports: [], settings: { pro: { enabled: false } } };
}

export async function loadState(): Promise<StorePulseState> {
  const raw = await browser.storage.local.get(STORAGE_KEY);
  const stored = raw[STORAGE_KEY] as StorePulseState | undefined;
  return stored?.version === 1 ? stored : empty();
}

export async function saveReport(report: StoreReport): Promise<void> {
  const state = await loadState();
  state.reports = [report, ...state.reports.filter((r) => r.id !== report.id)].slice(0, 40);
  await browser.storage.local.set({ [STORAGE_KEY]: state });
}

export async function listReports(): Promise<StoreReport[]> {
  return (await loadState()).reports;
}

export async function clearReports(): Promise<void> {
  const state = await loadState();
  state.reports = [];
  await browser.storage.local.set({ [STORAGE_KEY]: state });
}

export function formatClientReport(report: StoreReport): string {
  const lines = [
    `# StorePulse report — ${report.storeLabel}`,
    `URL: ${report.url}`,
    `Checked: ${new Date(report.checkedAt).toLocaleString()}`,
    `Score: ${report.score}/100`,
    '',
    ...report.checks.map((c) => `- [${c.severity.toUpperCase()}] ${c.label}: ${c.detail}`),
    '',
    '_Generated by StorePulse_',
  ];
  return lines.join('\n');
}
