import { STORAGE_KEY, type AuditEntry, type EntryKind, type PromptLedgerState } from './types';

function empty(): PromptLedgerState {
  return {
    version: 1,
    entries: [],
    settings: { defaultClientTag: '', pro: { enabled: false } },
  };
}

export async function loadState(): Promise<PromptLedgerState> {
  const raw = await browser.storage.local.get(STORAGE_KEY);
  const stored = raw[STORAGE_KEY] as PromptLedgerState | undefined;
  return stored?.version === 1 ? stored : empty();
}

export async function saveState(state: PromptLedgerState): Promise<void> {
  await browser.storage.local.set({ [STORAGE_KEY]: state });
}

export async function addEntry(input: {
  kind: EntryKind;
  text: string;
  sourceUrl?: string;
  sourceTitle?: string;
  clientTag?: string;
}): Promise<AuditEntry> {
  const state = await loadState();
  const entry: AuditEntry = {
    id: crypto.randomUUID(),
    kind: input.kind,
    text: input.text.trim(),
    sourceUrl: input.sourceUrl ?? '',
    sourceTitle: input.sourceTitle ?? '',
    clientTag: (input.clientTag ?? state.settings.defaultClientTag).trim(),
    createdAt: Date.now(),
  };
  if (!entry.text) throw new Error('Empty capture');
  state.entries.unshift(entry);
  state.entries = state.entries.slice(0, 500);
  await saveState(state);
  return entry;
}

export async function deleteEntry(id: string): Promise<void> {
  const state = await loadState();
  state.entries = state.entries.filter((e) => e.id !== id);
  await saveState(state);
}

export async function clearEntries(): Promise<void> {
  const state = await loadState();
  state.entries = [];
  await saveState(state);
}

export function exportMarkdown(entries: AuditEntry[], clientFilter?: string): string {
  const rows = clientFilter
    ? entries.filter((e) => e.clientTag.toLowerCase() === clientFilter.toLowerCase())
    : entries;
  const lines = [
    '# PromptLedger AI work audit',
    `Exported: ${new Date().toISOString()}`,
    clientFilter ? `Client: ${clientFilter}` : 'Client: (all)',
    '',
  ];
  for (const e of rows) {
    lines.push(`## ${e.kind.toUpperCase()} — ${new Date(e.createdAt).toLocaleString()}`);
    if (e.clientTag) lines.push(`Client tag: ${e.clientTag}`);
    if (e.sourceUrl) lines.push(`Source: [${e.sourceTitle || e.sourceUrl}](${e.sourceUrl})`);
    lines.push('');
    lines.push('```');
    lines.push(e.text);
    lines.push('```');
    lines.push('');
  }
  lines.push('_Generated by PromptLedger_');
  return lines.join('\n');
}
