import {
  DEFAULT_TEMPLATES,
  STORAGE_KEY,
  type ChecklistItem,
  type EvidenceItem,
  type EvidenceKitState,
} from './types';

function empty(): EvidenceKitState {
  return {
    version: 1,
    items: [],
    templates: DEFAULT_TEMPLATES.map((t) => ({ ...t })),
    settings: { pro: { enabled: false } },
  };
}

export async function loadState(): Promise<EvidenceKitState> {
  const raw = await browser.storage.local.get(STORAGE_KEY);
  const stored = raw[STORAGE_KEY] as EvidenceKitState | undefined;
  if (!stored || stored.version !== 1) {
    const seeded = empty();
    await browser.storage.local.set({ [STORAGE_KEY]: seeded });
    return seeded;
  }
  return stored;
}

export async function saveState(state: EvidenceKitState): Promise<void> {
  await browser.storage.local.set({ [STORAGE_KEY]: state });
}

export async function addEvidence(input: Omit<EvidenceItem, 'id' | 'capturedAt'>): Promise<EvidenceItem> {
  const state = await loadState();
  const item: EvidenceItem = {
    ...input,
    id: crypto.randomUUID(),
    capturedAt: Date.now(),
  };
  state.items.unshift(item);
  state.items = state.items.slice(0, 80);
  await saveState(state);
  return item;
}

export async function deleteEvidence(id: string): Promise<void> {
  const state = await loadState();
  state.items = state.items.filter((i) => i.id !== id);
  await saveState(state);
}

export async function updateChecklist(id: string, checklist: ChecklistItem[]): Promise<void> {
  const state = await loadState();
  const item = state.items.find((i) => i.id === id);
  if (!item) return;
  item.checklist = checklist;
  await saveState(state);
}

export function checklistFromTemplate(labels: string[]): ChecklistItem[] {
  return labels.map((label) => ({
    id: crypto.randomUUID(),
    label,
    done: false,
  }));
}

export function exportEvidenceMarkdown(item: EvidenceItem): string {
  return [
    `# EvidenceKit — ${item.title}`,
    `Captured: ${new Date(item.capturedAt).toISOString()}`,
    `URL: ${item.url}`,
    `Page: ${item.pageTitle}`,
    '',
    '## Checklist',
    ...item.checklist.map((c) => `- [${c.done ? 'x' : ' '}] ${c.label}`),
    '',
    '## Notes',
    item.note || '_None_',
    '',
    '## Screenshot',
    item.screenshotDataUrl
      ? '_Screenshot stored in EvidenceKit (open the extension to view)._'
      : '_No screenshot_',
    '',
    '_Generated by EvidenceKit_',
  ].join('\n');
}
